package org.tudo.sse.resolution.releases;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.tudo.sse.resolution.FileNotFoundException;
import org.tudo.sse.utils.MavenCentralRepository;
import org.tudo.sse.utils.ResourceConnections;
import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.List;

/**
 * This implementation of IReleaseListProvider obtains a list of releases for a given GA-Tuple by parsing the
 * HTML overview generated by Maven Central when fetching a GA's base URI.
 *
 * @author Johannes Düsing
 */
public class HTMLBasedMavenReleaseListProvider implements IReleaseListProvider {

    // Singleton pattern implementation
    private static final HTMLBasedMavenReleaseListProvider instance = new HTMLBasedMavenReleaseListProvider();

    /**
     * Access the singleton instance of HtmlBasedMavenReleaseListProvider
     * @return The only instance of this class
     */
    public static HTMLBasedMavenReleaseListProvider getInstance() {
        return instance;
    }

    // Singleton pattern implementation
    private HTMLBasedMavenReleaseListProvider(){}

    @Override
    public List<String> getReleases(String groupId, String artifactId) throws IOException {

        InputStream content = null;
        try {
            URI libraryBase = MavenCentralRepository.buildLibraryBaseURI(groupId, artifactId);
            content = ResourceConnections.openInputStream(libraryBase);

            if(content != null){
                //https://repo1.maven.org/maven2/uk/org/retep/tools/math/
                Document document = Jsoup.parse(content, "UTF-8", "https://www.example.com");
                Element listElem = document.getElementById("contents");

                if(listElem == null){
                    // If there is only one version, the "list" seems to be in <body> => <pre>
                    final Element body = document.getElementsByTag("body").first();
                    listElem = body == null ? null : body.getElementsByTag("pre").first();

                    if(listElem == null)
                        throw new IOException("Could not locate HTML element with ID 'contents' in version list HTML");
                }

                List<String> versions = new ArrayList<String>();
                listElem.getElementsByTag("a").forEach( linkElem -> {
                    String hrefValue = linkElem.attr("href");

                    if(!hrefValue.equals("../") && hrefValue.endsWith("/")){
                        versions.add(hrefValue.substring(0, hrefValue.length() - 1));
                    }
                });

                return versions;
            } else {
                throw new IOException("Failed to open HTML connection to " + libraryBase);
            }

        } catch (URISyntaxException | FileNotFoundException x){
            throw new IOException(x);
        } finally {
            if(content != null)
                content.close();
        }
    }

}
